# Generated by Django 6.0.3 on 2026-04-09 06:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'оборудование',
                'verbose_name_plural': 'оборудование',
                'db_table': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'помещение',
                'verbose_name_plural': 'помещения',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время начала заказа', verbose_name='дата и время начала')),
                ('date_time_end', models.DateTimeField(blank=True, help_text='Дата и время окончания заказа (оставьте пустым, если заказ активен)', null=True, verbose_name='дата и время окончания')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'orders',
                'ordering': ['-date_time_start'],
            },
        ),
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'тип оборудования',
                'verbose_name_plural': 'типы оборудования',
                'db_table': 'types_equipments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Введите количество от 1 до 999 (максимум 3 знака)', validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть не менее 1'), django.core.validators.MaxValueValidator(999, message='Количество не может превышать 999 (максимум 3 знака)')], verbose_name='количество')),
                ('id_equipments', models.ForeignKey(db_column='id_equipments', on_delete=django.db.models.deletion.CASCADE, to='mainapp.equipment', verbose_name='оборудование')),
                ('id_locations', models.ForeignKey(db_column='id_locations', on_delete=django.db.models.deletion.CASCADE, to='mainapp.location', verbose_name='помещение')),
                ('id_types_equipments', models.ForeignKey(db_column='id_types_equipments', on_delete=django.db.models.deletion.CASCADE, to='mainapp.typeequipment', verbose_name='тип оборудования')),
            ],
            options={
                'verbose_name': 'оборудование в помещении',
                'verbose_name_plural': 'оборудование в помещении',
                'db_table': 'equipments_locations',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('photo', models.ImageField(help_text='Загрузите фото в формате JPG', upload_to='location_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), mainapp.models.validate_jpg], verbose_name='фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('id_location', models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mainapp.location', verbose_name='помещение')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
                'db_table': 'photos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество от 1 до 999 (максимум 3 знака)', validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть не менее 1'), django.core.validators.MaxValueValidator(999, message='Количество не может превышать 999')], verbose_name='количество')),
                ('equipment_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='mainapp.equipmentlocation', verbose_name='оборудование в локации')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='mainapp.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'позиция заказа',
                'verbose_name_plural': 'позиции заказов',
                'db_table': 'order_items',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 999)), name='order_item_quantity_range_check')],
            },
        ),
        migrations.AddConstraint(
            model_name='equipmentlocation',
            constraint=models.UniqueConstraint(fields=('id_types_equipments', 'id_equipments', 'id_locations'), name='unique_equipment_location'),
        ),
        migrations.AddConstraint(
            model_name='equipmentlocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 999)), name='quantity_range_check'),
        ),
    ]
