# Generated by Django 6.0.3 on 2026-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-is_main', '-created_at'], 'verbose_name': 'фотография', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AddField(
            model_name='photo',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Отметьте, если это фото должно отображаться как главное для помещения', verbose_name='главное фото'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('id_location',), name='unique_main_photo_per_location'),
        ),
    ]
