# Generated by Django 6.0.3 on 2026-04-20 07:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_photo_options_photo_is_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonEquipmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Введите количество от 1 до 999 (максимум 3 знака)', validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть не менее 1'), django.core.validators.MaxValueValidator(999, message='Количество не может превышать 999 (максимум 3 знака)')], verbose_name='количество')),
                ('id_equipments', models.ForeignKey(db_column='id_equipments', on_delete=django.db.models.deletion.CASCADE, to='mainapp.equipment', verbose_name='оборудование')),
                ('id_types_equipments', models.ForeignKey(db_column='id_types_equipments', on_delete=django.db.models.deletion.CASCADE, to='mainapp.typeequipment', verbose_name='тип оборудования')),
            ],
            options={
                'verbose_name': 'общее оборудование',
                'verbose_name_plural': 'общее оборудование',
                'db_table': 'common_equipments_locations',
                'constraints': [models.UniqueConstraint(fields=('id_types_equipments', 'id_equipments'), name='unique_common_equipment'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 999)), name='common_quantity_range_check')],
            },
        ),
    ]
