# Generated by Django 6.0.3 on 2026-04-20 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_commonequipmentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_location',
            field=models.ForeignKey(blank=True, db_column='id_location', help_text='Выберите помещение (если заказ привязан к конкретному помещению)', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.location', verbose_name='помещение'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='common_equipment_location',
            field=models.ForeignKey(blank=True, help_text='Выберите общее оборудование (не привязанное к локации)', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.commonequipmentlocation', verbose_name='общее оборудование'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='equipment_location',
            field=models.ForeignKey(blank=True, help_text='Выберите оборудование из конкретной локации', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.equipmentlocation', verbose_name='оборудование в локации'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('common_equipment_location__isnull', True), ('equipment_location__isnull', False)), models.Q(('common_equipment_location__isnull', False), ('equipment_location__isnull', True)), _connector='OR'), name='one_of_equipment_locations_required'),
        ),
    ]
