# Generated by Django 6.0.3 on 2026-04-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_order_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительная информация к заказу', null=True, verbose_name='комментарий'),
        ),
    ]
