# Generated by Django 6.0.3 on 2026-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(error_messages={'unique': 'Оборудование с таким названием уже существует'}, max_length=100, unique=True, verbose_name='Наименование'),
        ),
    ]
