# Generated by Django 6.0.3 on 2026-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(error_messages={'unique': 'Помещение с таким названием уже существует'}, max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='typeequipment',
            name='name',
            field=models.CharField(error_messages={'unique': 'Тип оборудования с таким названием уже существует'}, max_length=100, unique=True, verbose_name='Наименование'),
        ),
    ]
