# Generated by Django 6.0.3 on 2026-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_location_description_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(default=1, max_length=300, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(error_messages={'unique': 'Помещение с таким названием уже существует'}, max_length=100, unique=True, verbose_name='Наименование'),
        ),
    ]
