# Generated by Django 6.0.3 on 2026-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_location_description_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание помещения', null=True, verbose_name='Описание'),
        ),
    ]
