# Generated by Django 6.0.3 on 2026-04-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание помещения. Поддерживает HTML теги.', null=True, verbose_name='Описание'),
        ),
    ]
