# Generated by Django 6.0.3 on 2026-04-22 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_location_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Введите название заявки', verbose_name='название заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заявки', verbose_name='дата создания')),
                ('comment', models.TextField(blank=True, help_text='Дополнительный комментарий к заявке', null=True, verbose_name='комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=50, verbose_name='статус')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='id_application',
            field=models.ForeignKey(blank=True, db_column='id_application', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.application', verbose_name='заявка'),
        ),
    ]
