# Generated by Django 6.0.3 on 2026-04-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_application_order_id_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_time_start'], 'verbose_name': 'аренда зала', 'verbose_name_plural': 'аренда залов'},
        ),
    ]
