# Generated by Django 6.0.3 on 2026-04-24 07:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_order_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Подробное описание действия пользователя', verbose_name='Описание действия')),
                ('datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'История действий',
                'ordering': ['-datetime'],
                'indexes': [models.Index(fields=['user', '-datetime'], name='mainapp_his_user_id_133a76_idx'), models.Index(fields=['datetime'], name='mainapp_his_datetim_ebc945_idx')],
            },
        ),
    ]
