# Generated by Django 6.0.3 on 2026-04-28 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Текст обратной связи/комментария', verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания отзыва', verbose_name='дата создания')),
                ('id_application', models.ForeignKey(db_column='id_application', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='mainapp.application', verbose_name='заявка')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_user', '-created_at'], name='feedback_id_user_df5088_idx'), models.Index(fields=['id_application'], name='feedback_id_appl_95fc90_idx'), models.Index(fields=['created_at'], name='feedback_created_6823e4_idx')],
            },
        ),
    ]
