# Generated by Django 6.0.3 on 2026-04-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id_application',
            field=models.ForeignKey(blank=True, db_column='id_application', help_text='Заявка, к которой оставлен отзыв (может быть не указана для общего отзыва)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='mainapp.application', verbose_name='заявка'),
        ),
    ]
