# Generated by Django 6.0.3 on 2026-04-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_feedback_id_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, help_text='Название отзыва/заголовок (необязательно)', max_length=300, null=True, verbose_name='название'),
        ),
    ]
