# Generated by Django 6.0.3 on 2026-04-29 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_feedback_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название подразделения (например, "Отдел продаж", "IT-отдел")', max_length=255, verbose_name='название подразделения')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='дата обновления')),
                ('id_user', models.ForeignKey(db_column='id_user', help_text='Пользователь, принадлежащий подразделению', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'подразделения',
                'db_table': 'departments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='departments_name_c59a45_idx'), models.Index(fields=['id_user'], name='departments_id_user_515d72_idx')],
                'unique_together': {('id_user',)},
            },
        ),
    ]
