# Generated by Django 6.0.3 on 2026-04-30 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField(default=False, help_text='Является ли пользователь руководителем подразделения', verbose_name='руководитель')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания связи', verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'связь пользователя с подразделением',
                'verbose_name_plural': 'связи пользователей с подразделениями',
                'db_table': 'user_departments',
                'ordering': ['id_department', 'id_user'],
            },
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='departments_id_user_515d72_idx',
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительное описание подразделения', null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Название подразделения (например, "Отдел продаж", "IT-отдел")', max_length=255, unique=True, verbose_name='название подразделения'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='id_department',
            field=models.ForeignKey(db_column='id_department', help_text='Подразделение', on_delete=django.db.models.deletion.CASCADE, related_name='department_users', to='mainapp.department', verbose_name='подразделение'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='user_departments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='id_user',
        ),
        migrations.AddIndex(
            model_name='userdepartment',
            index=models.Index(fields=['id_user'], name='user_depart_id_user_6bd8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='userdepartment',
            index=models.Index(fields=['id_department'], name='user_depart_id_depa_42dae0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdepartment',
            unique_together={('id_user', 'id_department')},
        ),
    ]
