# Generated by Django 6.0.3 on 2026-04-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_userdepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_end',
            field=models.DateTimeField(blank=True, help_text='Дата и время окончания заявки', null=True, verbose_name='дата окончания заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='date_start',
            field=models.DateTimeField(blank=True, help_text='Дата и время начала заявки', null=True, verbose_name='дата начала заявки'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_event',
            field=models.BooleanField(default=False, help_text='Отметьте, если помещение используется для мероприятий', verbose_name='мероприятие'),
        ),
    ]
