# Generated by Django 6.0.3 on 2026-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_application_date_end_application_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_event',
            field=models.BooleanField(default=True, help_text='Отметьте, если помещение используется для мероприятий', verbose_name='мероприятие'),
        ),
    ]
