# Generated by Django 6.0.3 on 2026-05-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_location_is_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_approval_required',
            field=models.BooleanField(default=False, help_text='Отметьте, если для заявок этого подразделения требуется согласование', verbose_name='требуется согласование'),
        ),
    ]
