# Generated by Django 6.0.3 on 2026-05-05 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_department_is_approval_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='is_approval_required',
            field=models.BooleanField(default=False, help_text='Отметьте, если данное подразделение учавствует в согласовании заявок', verbose_name='Согласование'),
        ),
        migrations.CreateModel(
            name='DepartmentTypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания связи', verbose_name='дата создания')),
                ('id_department', models.ForeignKey(db_column='id_department', help_text='Подразделение', on_delete=django.db.models.deletion.CASCADE, related_name='department_type_equipment', to='mainapp.department', verbose_name='подразделение')),
                ('id_type_equipment', models.ForeignKey(db_column='id_type_equipment', help_text='Тип оборудования', on_delete=django.db.models.deletion.CASCADE, related_name='department_type_equipment', to='mainapp.typeequipment', verbose_name='тип оборудования')),
            ],
            options={
                'verbose_name': 'связь подразделения с типом оборудования',
                'verbose_name_plural': 'связи подразделений с типами оборудования',
                'db_table': 'departments_types_equipment',
                'ordering': ['id_department', 'id_type_equipment'],
                'indexes': [models.Index(fields=['id_department'], name='departments_id_depa_19bf36_idx'), models.Index(fields=['id_type_equipment'], name='departments_id_type_b0e915_idx')],
                'unique_together': {('id_department', 'id_type_equipment')},
            },
        ),
    ]
