# Generated by Django 6.0.3 on 2026-05-05 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_department_is_approval_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='can_provide',
            field=models.IntegerField(default=0, help_text='Количество оборудования, которое может предоставить подразделение (0 - не может предоставить)', validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть меньше 0')], verbose_name='может предоставить'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_agreed',
            field=models.BooleanField(default=False, help_text='Отметьте, если позиция согласована', verbose_name='согласовано'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('can_provide__gte', 0)), name='order_item_can_provide_range_check'),
        ),
    ]
