# Generated by Django 6.0.3 on 2026-05-05 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_orderitem_can_provide_orderitem_is_agreed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='can_provide',
            field=models.IntegerField(default=0, help_text='Количество оборудования, которое может предоставить подразделение (0 - не может предоставить)', validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть меньше 0')], verbose_name='можем предоставить'),
        ),
        migrations.CreateModel(
            name='ApplicationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_agreed', models.BooleanField(default=False, help_text='Статус согласования заявки подразделением', verbose_name='согласовано')),
                ('date_agreed', models.DateTimeField(blank=True, help_text='Дата и время согласования (заполняется автоматически при is_agreed=True)', null=True, verbose_name='дата согласования')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к согласованию', null=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления', verbose_name='дата обновления')),
                ('id_application', models.ForeignKey(db_column='id_application', help_text='Заявка на согласование', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='mainapp.application', verbose_name='заявка')),
                ('id_department', models.ForeignKey(db_column='id_department', help_text='Подразделение, которое согласовывает заявку', on_delete=django.db.models.deletion.CASCADE, related_name='application_approvals', to='mainapp.department', verbose_name='подразделение')),
            ],
            options={
                'verbose_name': 'согласование заявки',
                'verbose_name_plural': 'согласование заявок',
                'db_table': 'application_approvals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_department'], name='application_id_depa_418578_idx'), models.Index(fields=['id_application'], name='application_id_appl_964fc7_idx'), models.Index(fields=['is_agreed'], name='application_is_agre_e35fd1_idx'), models.Index(fields=['date_agreed'], name='application_date_ag_e8263b_idx')],
                'unique_together': {('id_department', 'id_application')},
            },
        ),
    ]
