# Generated by Django 6.0.3 on 2026-05-05 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_orderitem_can_provide_applicationapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationapproval',
            name='id_user',
            field=models.ForeignKey(blank=True, db_column='id_user', help_text='Пользователь, который согласовал заявку', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_approvals', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddIndex(
            model_name='applicationapproval',
            index=models.Index(fields=['id_user'], name='application_id_user_12c777_idx'),
        ),
    ]
