# Generated by Django 6.0.3 on 2026-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные данные в формате JSON (например, браузер, ОС, URL страницы и т.д.)', null=True, verbose_name='дополнительные данные'),
        ),
    ]
