# Generated by Django 6.0.3 on 2026-05-08 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_feedback_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные данные в формате JSON (оценка мероприятия, отзыв о проведении и т.д.)', null=True, verbose_name='дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id_application',
            field=models.ForeignKey(blank=True, db_column='id_application', help_text='Заявка, к которой оставлен отзыв', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='mainapp.application', verbose_name='заявка'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, help_text='Название отзыва/заголовок', max_length=300, null=True, verbose_name='название'),
        ),
    ]
