# Generated by Django 6.0.3 on 2026-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_feedback_data_alter_feedback_id_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_slot',
            field=models.BooleanField(default=False, help_text='Отметьте, если эта позиция относится к слоту', verbose_name='признак слота'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slot_date_end',
            field=models.DateTimeField(blank=True, help_text='Дата и время окончания слота (заполняется для слотов)', null=True, verbose_name='дата окончания слота'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slot_date_start',
            field=models.DateTimeField(blank=True, help_text='Дата и время начала слота (заполняется для слотов)', null=True, verbose_name='дата начала слота'),
        ),
    ]
